#!/usr/bin/env bash

# Install homebrew
# @see https://docs.brew.sh/Installation
[[ -z $(command -v brew) ]] && /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"


# Install oh-my-zsh
# @see https://ohmyz.sh/#install
[[ ! -d $HOME/.oh-my-zsh ]] && curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh


# Install sdkman(java version management)
# @see https://sdkman.io/install
[[ -z $(command -v sdk) ]] && curl -s "https://get.sdkman.io" | bash
