#!/usr/bin/env bash

# Install homebrew without sudo
# @see https://docs.brew.sh/Installation
[[ -z $(command -v brew) ]] && mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
chmod +x homebrew/bin/brew
cp homebrew/bin/brew /opt/brew


# Install oh-my-zsh
# @see https://ohmyz.sh/#install
[[ ! -d $HOME/.oh-my-zsh ]] && curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash


# Install sdkman(java version management)
# @see https://sdkman.io/install
[[ -z $(command -v sdk) ]] && curl -s "https://get.sdkman.io" | bash
