#!/usr/bin/env bash

info () {
  printf "\r  [ \033[0;33mINFO\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;SUCCESS\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  exit 1
}
